spring.application.name=SecurityApplication

spring.datasource.url=jdbc:mysql://localhost:3306/security-app?useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=Karan@1234five

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#security configs
#spring.security.user.name=karan
#spring.security.user.password=fuckyou
